apiVersion: v1
kind: Deployment
metadata:
  name: techtrends
  namespace: sandbox
  labels:
    app: techtrends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: meladsamuel/techtrends
        imagePullPolicy: IfNotPresent
        name: techtrends
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
        ports:
        - containerPort: 3111
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
            httpHeaders:
            - name: Accept
              value: application/json
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
            httpHeaders:
            - name: Accept
              value: application/json
          initialDelaySeconds: 3
          periodSeconds: 3
